### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by uiguosun** [kailous/Figma-UI3-Surge#2]
你好作者我按照你提供的方法步骤进行后，但我的 figma 并没有任何变化，可以抽时间帮我看一下吗，谢谢！
![Uploading 截屏2024-07-23 09.35.58.png…]()

**Comment by kailous** [comment]
你上传的截图 打不开呢 粘贴图片后 要过一会儿才能到图床

注意看下 https 解密 这部分的设置
![image](https://github.com/user-attachments/assets/f1f64f90-ee18-4535-b8d2-1df7005c9605)
这个功能 一定要打开
生成新的证书后 一定要安装到系统
MitM 一定要写主机名 一定要写 *.figma.com
选项中 三个钩子 最好要勾上
另外检查脚本配置
![image](https://github.com/user-attachments/assets/a1eb94a8-6e7a-4573-9a60-7f5828aed152)
1. 确保脚本路径正确
2. 表达式正确
3. 超时这个可以尝试为1
4. 然后是 最后一个 数据体尺寸 为 无限制

**Comment by uiguosun** [comment]
可当我把 js 文件移动到“Profiles”文件夹后，surge 没有办法识别出来






---- 回复的原邮件 ----
| 发件人 | Li ***@***.***> |
| 发送日期 | 2024年7月24日 14:04 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [kailous/Figma-UI3-Surge] 问题请教 (Issue #2) |

你上传的截图 打不开呢 粘贴图片后 要过一会儿才能到图床

注意看下 https 解密 这部分的设置
image.png (view on web)
这个功能 一定要打开
生成新的证书后 一定要安装到系统
MitM 一定要写主机名 一定要写 *.figma.com
选项中 三个钩子 最好要勾上
另外检查脚本配置
image.png (view on web)

确保脚本路径正确
表达式正确
超时这个可以尝试为1
然后是 最后一个 数据体尺寸 为 无限制
